### PR TITLE
feat(bahnhofshalle): migrate to parcel for building

### PR DESCRIPTION
**Pull request by sternenseemann**
We get

* rid of redo
* minified assets
* output hashes (for aggressive caching)
* ~~more yarn2nix woes~~ simpler `bahnhofshalle` package

### CODE REVIEW

**Comment by sternenseemann** [comment]
Open questions:

* [ ] Is the experimental `linkNodeDeps` correct?
* [ ] Can it be faster?

**Comment by Profpatsch** [comment]
Should we merge?

**Comment by sternenseemann** [comment]
It would be cleaner than what we have now, but I'm not satisfied with the nix side of things which is why I have been holding of on merging this. Basically I'd either like to figure out the rest of `yarn2nix` or maybe use `node2nix` or the likes for shipping the parcel build env…

**Comment by sternenseemann** [comment]
Will merge this now with node2nix instead of yarn2nix. This should make the build process faster and I'm not comfortable pinning some yarn2nix branch of mine with the `node_modules` with the whole dependency tree half-figured out.

I don't really like node2nix, but it's the cleanest solution for getting `parcel` to work and build with nix at the moment. I will revert back to yarn2nix as soon as I have the correct linkNodeDeps figured out and merged :)

**Pull request merged**
